version: '3.9'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
