
FROM node:20-alpine


WORKDIR /app


RUN apk add --no-cache libc6-compat

RUN mkdir -p .next/cache/images \
    && mkdir -p cv-uploads \
    && chown -R node:node .next cv-uploads \
    && chmod -R 755 .next \
    && chmod -R 700 cv-uploads


COPY package.json package-lock.json* ./


RUN npm install


COPY prisma ./prisma/
COPY .env* ./


COPY . .


RUN chown -R node:node ./cv-uploads \
    && chmod -R 700 ./cv-uploads


USER node


EXPOSE 3000


CMD ["npm", "run", "dev"]
